// Generated by flute sync. Edit recipes and components, not this registry.
import recipe0 from "./scenes/landing-page.scene.json";
export const sceneModules = {
  "src/flute/scenes/landing-page.scene.json": async () => ({default:recipe0}),
  "src/flute/scenes/landing-page.tsx": () => import("./scenes/landing-page"),
};
